// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKY0KN2q7hvA6HwLm0CwunMJL1Gc9sDwE',
    appId: '1:489386869256:web:b152d01715af83be0fc7bd',
    messagingSenderId: '489386869256',
    projectId: 'groupify-9c96f',
    authDomain: 'groupify-9c96f.firebaseapp.com',
    storageBucket: 'groupify-9c96f.firebasestorage.app',
    measurementId: 'G-VBPQ5ZE8MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ojUKH4c4iSmr5LqdMf8USbMFyLbNhcQ',
    appId: '1:489386869256:android:18d1cb50088933fb0fc7bd',
    messagingSenderId: '489386869256',
    projectId: 'groupify-9c96f',
    storageBucket: 'groupify-9c96f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB4nMbA2_WfbxnSpfWXJrU1f255wSlt5A',
    appId: '1:489386869256:ios:ba9973ce1967af2e0fc7bd',
    messagingSenderId: '489386869256',
    projectId: 'groupify-9c96f',
    storageBucket: 'groupify-9c96f.firebasestorage.app',
    iosBundleId: 'com.example.groupify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB4nMbA2_WfbxnSpfWXJrU1f255wSlt5A',
    appId: '1:489386869256:ios:ba9973ce1967af2e0fc7bd',
    messagingSenderId: '489386869256',
    projectId: 'groupify-9c96f',
    storageBucket: 'groupify-9c96f.firebasestorage.app',
    iosBundleId: 'com.example.groupify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKY0KN2q7hvA6HwLm0CwunMJL1Gc9sDwE',
    appId: '1:489386869256:web:bb84e17b3f11018d0fc7bd',
    messagingSenderId: '489386869256',
    projectId: 'groupify-9c96f',
    authDomain: 'groupify-9c96f.firebaseapp.com',
    storageBucket: 'groupify-9c96f.firebasestorage.app',
    measurementId: 'G-ETK989D4MZ',
  );
}
